#!/usr/bin/env python
import sys
import time
tick = time.time()

import argparse

import speckle


parser = argparse.ArgumentParser(description="Plot NESSI data")
parser.add_argument('-i', '--id', help='ID', type=str, default=None)
parser.add_argument('-d', '--data_dir', help='Directory containing NESSI data products',
    type=str, default='.')
parser.add_argument('-s', '--stretch', help='y-axis stretch factor (default=1)', type=float, default=1)
parser.add_argument('-n', '--name', help='Target name', type=str, default=None)
parser.add_argument('-v', '--vrange', help='Log stretch vrange', type=str, default=None)
parser.add_argument('-c', '--cmap', help='Color map name', type=str, default=None)
args = parser.parse_args()

if args.id is None:
    sys.exit('Must supply ID')

id_ = args.id
data_dir = args.data_dir
stretch = args.stretch
name = args.name
vrange = args.vrange
cmap = args.cmap

if vrange is not None:
    vrange = list(map(float,vrange.split(',')))

spkl = speckle.Speckle(id_, data_dir)
spkl.plot(title=name, stretch=stretch, vrange=vrange, cmap=cmap)

print("Script executed in {0:.1f} seconds\n".format(time.time() - tick))
